/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/error/403.vue')['default']
    404: typeof import('./src/components/error/404.vue')['default']
    500: typeof import('./src/components/error/500.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    BaseChart: typeof import('./src/components/echarts/base-chart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
  }
}
